### ISSUE TITLE
Update to v1

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/datapackage-rb#29]
# Description

V1 of the Data Package and Tabular Data Package specs are in release candidate stage. The [Python](https://github.com/frictionlessdata/datapackage-py) and [Javascript](https://github.com/frictionlessdata/datapackage-js) libraries have been updated. While there are still a couple of things unresolved, this library can be updated to support V1 of the specs now.

# Tasks

- [x] Review the whole family of [specifications](http://specs.frictionlessdata.io)
- [x] Review the [implementation notes](http://specs.frictionlessdata.io/implementation/)
- [x] Review either the Python ([Data Package](https://github.com/frictionlessdata/datapackage-py) [Table Schema](https://github.com/frictionlessdata/tableschema-py)) or JavaScript ([Data Package](https://github.com/frictionlessdata/datapackage-js) [Table Schema](https://github.com/frictionlessdata/tableschema-js)) reference implementations (whichever language you feel most comfortable reading)
- [x] Review the [stack reference](https://github.com/frictionlessdata/stack#frictionless-data-stack)
- [x] Review the blog post that announces [v1 of the specifications](https://hackmd.io/KwUzE5wIwRgWgGYENzDgFmAgzHKA2fJOABmHwGMATEmK8GIoA===)
- [x] Review the test packages that can be used to [test your work](https://github.com/frictionlessdata/testsuite-py/tree/master/datasets) (in addition to the normal and expected unit tests)
- [x] Review the [OKFN Coding Standards](https://github.com/okfn/coding-standards)
  - Parts of the coding standard are language specific, and parts are workflow specific. The workflow points are important for you. If you want to contribute language-related standards to our docs for your language, we welcome it!
- [x] Write a set of high-level issues for each library, on the respective issue tracker, that outline the work plan. Do this with some feedback from @roll who has done V1 updates for the Python and Javascript libraries
  - Note the structure of this issue: A narrative description and a specific list of tasks. Follow a similar pattern
  -  The sequence of work is important: start with the Table Schema library first, as the Data Package library has a direct dependency on it

**Comment by georgiana-b** [comment]
The issues concerned with updating this gem to [Table Schema v1-spec](http://specs.frictionlessdata.io/table-schema/) can be found [under `Version-1` label](https://github.com/frictionlessdata/tableschema-rb/labels/Version-1).
