### ISSUE TITLE
Update Resource class

### ISSUE THREAD

**Issue by georgiana-b** [frictionlessdata/datapackage-rb#30]
# Overview

The Resource class has to be brought in line with v1 spec. 
The steps below are based on the release candidate spec rc2 and may be changed by the time this issues gets solved so make sure to check the latest spec before implementing 

# Tasks

- [x]  `path` also keeps urls now. Convert `url` to `path` for backward compatibility
- [x]  make `name` required property
- [ ]  add `media_type`/`format` to help identify inline `data` that is a string
- [x]  add `descriptor` to access the resource object
- [x]  add functionality to treat tabular resources:
    - [x]  `tabular` boolean property
    - [x]  `table` method that makes a [`tableschema.Table`](https://github.com/frictionlessdata/tableschema-rb) from the resource ([details](https://github.com/frictionlessdata/implementations#datapackage))
- [ ] update all other lib code to work with updated `Resource`

**Comment by roll** [comment]
@georgiana-b 
Both implementations are mostly the same now (py ported to js):
- https://github.com/frictionlessdata/datapackage-py/blob/master/datapackage/resource.py
- https://github.com/frictionlessdata/datapackage-js/blob/master/src/resource.js

So for Ruby it seems you just sync it with Py/JS. Only massive logic for this class is handling different types of sources (local/remote/etc)

Also I've moved from this issue support for multipart resources - https://github.com/frictionlessdata/datapackage-rb/issues/37 (priority is low and could take a while so please just raise NotImplemented for now as JavaScript does)

**Comment by roll** [comment]
@georgiana-b 
Alsmost everything you need to finish this one is in https://github.com/frictionlessdata/datapackage-js/pull/76
